### ISSUE TITLE
getting some nodejs event error

### ISSUE THREAD

**Issue by PapaSimons** [tylerbuchea/cordova-android-crosswalk#5]
After running  crosswalk-cordova-android I get the following:

Gideons-MacBook-Pro:Verse PapaSimons$ sudo crosswalk-cordova-android
Found SDK target: android-19
Removed old Crosswalk stable
     fetch : https://download.01.org/crosswalk/releases/crosswalk/android/stable/8.37.189.12/arm/crosswalk-cordova-8.37.189.12-arm.zip
  progress : [====================] 100% 0.0s

Crosswalk stable downloaded succesfully
Removed old CordovaLib
./platforms/android/CordovaLib was replaced with the Crosswalk stable framework
./platforms/android/VERSION file was replaced with Crosswalk VERSION file

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/crosswalk-cordova-android/bin/crosswalk-cordova-android:165:54
    at Parser.<anonymous> (/usr/local/lib/node_modules/crosswalk-cordova-android/node_modules/xml2js/lib/xml2js.js:384:20)
    at Parser.emit (events.js:95:17)
    at Object.onclosetag (/usr/local/lib/node_modules/crosswalk-cordova-android/node_modules/xml2js/lib/xml2js.js:348:26)
    at emit (/usr/local/lib/node_modules/crosswalk-cordova-android/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/usr/local/lib/node_modules/crosswalk-cordova-android/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
    at closeTag (/usr/local/lib/node_modules/crosswalk-cordova-android/node_modules/xml2js/node_modules/sax/lib/sax.js:861:5)
    at Object.write (/usr/local/lib/node_modules/crosswalk-cordova-android/node_modules/xml2js/node_modules/sax/lib/sax.js:1294:29)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/crosswalk-cordova-android/node_modules/xml2js/lib/xml2js.js:403:31)
    at Parser.parseString (/usr/local/lib/node_modules/crosswalk-cordova-android/node_modules/xml2js/lib/xml2js.js:6:61)

**Comment by tylerbuchea** [comment]
You're getting this error because your ./platforms/android/AndroidManifest.xml file has no permissions. I'm not sure why this is but you can fix this issue by adding these lines just before the existing <application> element. I'll add a catch to the code so this won't be a problem in the future.

<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />

**Comment by tylerbuchea** [comment]
Just added a catch all. This issue should be fixed now. Thanks for the heads up PapaSimons.
